spring:
  application:
    name: social-media-api
  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/social-media-bd
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  docker:
    compose:
      enabled: true
      lifecycle-management: start_and_stop

jwt:
  secret: dfsdfsd9fsdifosid6f8sflsi
  lifetime: 30m

#server:
#  port: 8080
